### ISSUE TITLE
Error: Your Command Line Tools are too outdated.

### ISSUE THREAD

**Issue by erlichmen** [allero-io/allero#14] opened 2022-08-29 18:43 UTC
I have xcode 13.4.1 and I get the above message (m1 mac) 

```
brew install allero-io/allero/allero

Already downloaded: /Users/erlichmen/Library/Caches/Homebrew/downloads/77842b251463ee9e209d38ca837db6ea724d3bf06e3b86129a001760b26156c7--allero_0.0.1_Darwin_x86_64.zip
Warning: Cannot verify integrity of '77842b251463ee9e209d38ca837db6ea724d3bf06e3b86129a001760b26156c7--allero_0.0.1_Darwin_x86_64.zip'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "315c14bc1781c9fa39c598f355eae1c80b32fe3f4956c95fe7254f026f0752bb"
==> Installing allero from allero-io/allero
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.4.
```

PS: curl install gives me the following:
```
curl https://get.allero.io | /bin/bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1294  100  1294    0     0   6158      0 --:--:-- --:--:-- --:--:--  6343
Installing Allero...


```

but it doesn't instal anything

**Comment by dimabru** [comment] 2022-08-30 07:25
Hey @erlichmen, thanks for reporting the issue. 
I'm having trouble reproducing this error. I'm using the same xcode version with m1 processor and the cli is working fine for me.

Any chance this article might help?
https://coady.tech/macos-command-line-tools-outdated/

**Comment by dimabru** [comment] 2022-09-18 08:18
Closing this issue. Unable to reproduce

**Closed by dimabru** 2022-09-18 08:18 UTC
Labels: bug
